export const mockQonevoContacts = [
  {
    id: 1,
    full_name: "Aarav Sharma",
    email: "aarav.sharma@techcorp.in",
    phone_number: "+91 98765 43210",
    company_name: "TechCorp Solutions",
    website_url: "https://techcorp.in",
    help_message: "We are interested in integrating Synergy interactive displays across our corporate offices in Mumbai and Bengaluru. Looking for a custom demo and pricing details.",
    created_at: "2026-08-30T10:15:00Z",
    source: "Qonevo"
  },
  {
    id: 2,
    full_name: "Priya Nair",
    email: "priya.nair@innovate.org",
    phone_number: "+91 98123 45678",
    company_name: "Innovate Next Labs",
    website_url: "https://innovatenext.org",
    help_message: "Need technical specifications for Qonevo IFP size options and S3 integration support. Please connect us with your product solution engineering team.",
    created_at: "2026-08-29T14:45:22Z",
    source: "Qonevo"
  },
  {
    id: 3,
    full_name: "Rohan Verma",
    email: "r.verma@synergydigital.com",
    phone_number: "+91 99001 12233",
    company_name: "Synergy Digital Media",
    website_url: "https://synergydigital.com",
    help_message: "Inquiring about bulk procurement of Qonevo smart boards for 15 secondary school campuses. Requesting a brochure and partnership terms.",
    created_at: "2026-08-28T09:30:10Z",
    source: "Qonevo"
  },
  {
    id: 4,
    full_name: "Ananya Mehta",
    email: "ananya@futureed.edu",
    phone_number: "+91 97654 32109",
    company_name: "FutureEd Academy",
    website_url: "https://futureed.edu",
    help_message: "Can you provide warranty terms, installation support timelines, and post-purchase maintenance plans for high-traffic training rooms?",
    created_at: "2026-08-27T16:20:00Z",
    source: "Qonevo"
  },
  {
    id: 5,
    full_name: "Vikram Sengupta",
    email: "vikram@apexsys.com",
    phone_number: "+91 98450 98765",
    company_name: "Apex Systems",
    website_url: "https://apexsys.com",
    help_message: "We want to order 5 units of 75-inch smart panels for our boardrooms. Please send us formal quotation and deployment schedule.",
    created_at: "2026-08-25T11:05:40Z",
    source: "Qonevo"
  }
];

export const mockMakerspaceEnquiries = [
  {
    id: 101,
    first_name: "Dr. Rajesh",
    last_name: "Kulkarni",
    email: "rajesh.kulkarni@dypatil.edu",
    phone: "+91 94220 11223",
    role: "Principal / Dean",
    institution: "D.Y. Patil Institute of Technology",
    organization_type: "Higher Education / University",
    location: "Pune, Maharashtra",
    students: "1500+",
    solution_interest: "Atal Tinkering Lab / Makerspace Lab setup",
    implementation_time: "Immediate (1-3 months)",
    comment: "We are setting up an advanced Robotics and IoT innovation lab under the Makerspace initiative. Need complete curriculum and hardware kit setup.",
    created_at: "2026-08-30T11:40:00Z",
    source: "Makerspace Site"
  },
  {
    id: 102,
    first_name: "Sneha",
    last_name: "Deshmukh",
    email: "sneha.d@greenwoodschool.in",
    phone: "+91 98234 56789",
    role: "STEM Coordinator",
    institution: "Greenwood International School",
    organization_type: "K-12 School",
    location: "Hyderabad, Telangana",
    students: "500-1000",
    solution_interest: "AI & Coding Modules for High School",
    implementation_time: "Next Academic Quarter",
    comment: "Looking to introduce Makerspace Arena competitions and project-based STEM modules for grades 6 through 10.",
    created_at: "2026-08-29T15:10:05Z",
    source: "Makerspace Site"
  },
  {
    id: 103,
    first_name: "Amitabh",
    last_name: "Choudhury",
    email: "amitabh.c@kolkatastem.org",
    phone: "+91 93310 99887",
    role: "Trustee / Management",
    institution: "Kolkata Innovation Foundation",
    organization_type: "Non-Profit / NGO Foundation",
    location: "Kolkata, West Bengal",
    students: "250-500",
    solution_interest: "Franchise & Community Makerspace Center",
    implementation_time: "Within 6 months",
    comment: "Interested in establishing a community Makerspace center with hands-on 3D printing and electronics kits for underprivileged youth.",
    created_at: "2026-08-28T13:25:30Z",
    source: "Makerspace Site"
  },
  {
    id: 104,
    first_name: "Meera",
    last_name: "Rao",
    email: "meera.rao@nationalpublic.ac.in",
    phone: "+91 97400 33445",
    role: "Head of Science Dept.",
    institution: "National Public School",
    organization_type: "K-12 School",
    location: "Bengaluru, Karnataka",
    students: "1000-1500",
    solution_interest: "Startup School Revolution Module",
    implementation_time: "Immediate (1-3 months)",
    comment: "We saw your Makerspace Masters curriculum. Please share details regarding teacher training workshops and student assessment kits.",
    created_at: "2026-08-26T08:50:12Z",
    source: "Makerspace Site"
  },
  {
    id: 105,
    first_name: "Sanjay",
    last_name: "Patel",
    email: "sanjay.patel@gujarattech.ac.in",
    phone: "+91 98980 54321",
    role: "Director of Innovation",
    institution: "Gujarat Technological University",
    organization_type: "State Technical University",
    location: "Ahmedabad, Gujarat",
    students: "2000+",
    solution_interest: "Incubation & Tinkering Ecosystem",
    implementation_time: "Within 6 months",
    comment: "Evaluating Makerspace Masters incubation model for our startup cell. Requesting a site visit or detailed presentation with your academic team.",
    created_at: "2026-08-24T17:30:00Z",
    source: "Makerspace Site"
  }
];
